library(tidyverse)
library(vegan)
library(GUniFrac) # smoker data set from this package 



# Mantel test and partial Mantel test 

# Ref. 
# 1) Chap 9.2 - Book: Statistical analysis of microbiome data with R 
# 2) GUSTA ME 

# mantel test is to test the hypothesis for linear relationship between two distance matrix, for example, 
# between species distance matrix (Bray-Curtis distance) and (standardized) environmental variables matrix
# In addition, partial mantel test can assess the relationship between matrix A and B with controlling for the 
# effect of matrix C, taking into consideration of possible spurious correlation. 

data("throat.otu.tab")

otu_table_matrix <- throat.otu.tab %>% as.matrix() 

data("throat.meta")

data("throat.tree")

throat_meta <- throat.meta %>% 
        select(SmokingStatus, Age, Sex, PackYears) 



# test Pearson's product-moment correlation of Bray-Curtis and Jaccard dissimilarity  
require(vegan)

bray <- vegdist(otu_table_matrix, method = "bray") # bray-curtis dissimilarity 
jaccard <- vegdist(otu_table_matrix, method = "jaccard")  # jaccard dissimilarity 

set.seed(19861015)
mantel(bray, jaccard, "pearson",  permutations = 1000) # mantel test to compare bray-curtis and jaccard matrix 
# interpretation: out of these 1000 values, none was larger than the observed value of 0.9957 (that is 
# number of permutations < observed = 1000, number of permutations > observed = 0; 
# number of permutations = observed =1), so that the chance of obtaining 
# a value as large as the observed is smaller than 1/1000, indicating a p value of 0.001. 
# In conclusion, because a large correlation generated by chance is so small, we can conclude that 
# Bray-Curtis distance difference increase linearly with Jaccard distances, in other words, these two dissimilarity 
# indices are highly positively correlated. 




# quick plot Pearson correlation of Bray-Curtis and Jaccard matrix 
plot(bray, jaccard, main = "Scatter plot of Bray-Curtis index vs. Jaccard index") 
# Pearson's coefficient r = 0.9957 with a p value of 0.001 



# test Pearson's rank correlation of Bray-Curtis and Sorensen dissimilarities 

# # define a function to convert count data to presence/absence data 
# is_binary <- function(x){
#         ifelse(x!=0, 1, 0)
# }
# 
# otu_table_binary <- otu_table %>% 
#         mutate_all(is_binary) %>%
#         as.matrix()

sor <- vegdist(decostand(otu_table_matrix, method = "pa"), # presence/absence data 
                      method = "bray") # calculate sorensen dissimilarities 

set.seed(19861015) 
mantel(bray, sor, "spearman", permutations = 1000) 




# Test Kendall's rank correlation of Jaccard and Sorensen dissimilarities 
mantel(jaccard, sor, "kendall", permutations = 1000)




# Test the correlation of a community matrix and a design matrix 
## smoking status from meta-data as the design matrix 
## to test whether the Bray-Curtis dissimilarities are different between samples from smokers and non-smokers 

group <- select(throat.meta, SmokingStatus)
group$Status <- with(group, ifelse(SmokingStatus %in% "Smoker", 1, 0)) 
group <- group[ ,-1] 
group_dist <- vegdist(scale(group), "euclid")  # generate a distance matrix based on the env variable of interest 

set.seed(19861015)
mantel(group_dist, bray, "pearson", permutations = 1000)  # correlation is weak but significant 





# Partial mantel test the correlation of two distance matrices controlling the third matrix 
## partial mental test is used to conduct correlation analysis of a community distance matrix and a design 
# distance matrix while controlling an env distance matrix 

# example: test correlation between Bray-Curtis distance matrix and smoking status when control the matrix with 
# age, gender, and pack per year

# see chap 9.2.2.3 for procedure under the hood 

meta <- select(throat.meta, Age, Sex, PackYears)

meta$Gender <- with(meta, ifelse(Sex %in% "Male", 1, 0)) 

env <- select(meta, Age, Gender, PackYears)  # recode factor variable into numeric 

env_dist <- vegdist(scale(env), "euclid") # env distance matrix 

require(19861015)
set.seed(123) 
mantel.partial(group_dist, bray, env_dist, 
               method = "pearson",
               permutations = 1000)
# interpretation: correlation between Bray-Curtis distance and smoking status 
# is weak (r=0.07) but significant (p<0.01) 

























